### ISSUE TITLE
Add support for newer versions of Flatcar using cgroup v2 and systemd cgroup driver

### ISSUE THREAD

**Issue by vpnachev** [gardener/gardener-extension-os-coreos#35]
**How to categorize this issue?**

/area os
/kind enhancement
/priority 3

**What would you like to be added**:
Add support for newer versions of Flatcar using cgroup v2 and systemd cgroup driver

1. Kubernetes <=v1.18 does not support cgroup v2, needs to be decided if this extension will support older k8s versions with newer Flatcar versions. The good thing is that k8s 1.18 is out of maintenance since long time and it is highly unlikely to be used.
1. cgroup v2 is not working with `cgroupfs` driver which is explicitly set in the [kubelet config](https://github.com/gardener/gardener/blob/bfd8cef1f1fe920b18dd65ffde7523702f9d7db9/pkg/operation/botanist/component/extensions/operatingsystemconfig/original/components/kubelet/config.go#L54). This extension needs to change it to `systemd`

More details what needs to be changed can be found in [this](https://www.flatcar-linux.org/docs/latest/container-runtimes/switching-to-unified-cgroups/#kubernetes) nice blog from Kinvolk.

**Why is this needed**:
To enable support for newer flatcar versions with this extension.

**Comment by christianhuening** [comment]
This essentially means flatcar 2905.2.6 is the last supported flatcar version until this is implemented/fixed, correct?

**Comment by vpnachev** [comment]
Most likely yes, I haven't tried to create a node with Flatcar > 2905.2.6, but guess it will not be succeed.

**Comment by dergeberl** [comment]
@vpnachev I am not 100% sure but a change of the default cgroup driver on the linked place can have a bigger impact, because it affect all different operating systems. Maybe it is better to add the possibility to configure it in the cloud profile. So the default can be overwritten if needed for an specific os and os version. For example a `cgroupDriver` field in `cloudprofile.spec.machineImages`. What do you think?

**Comment by christianhuening** [comment]
do i get it right, that this issue is pretty much depending/waiting on #5325 ?

**Comment by vpnachev** [comment]
Not necessary, this extension is able to amend the kubelet config and make the necessary configuration changes based on the flatcar version in /etc/os-release file. Alternatively, it can check if cgroup v2 is enabled via the presence of the file `/sys/fs/cgroup/cgroup.controllers` (ref: https://rootlesscontaine.rs/getting-started/common/cgroup2/#checking-whether-cgroup-v2-is-already-enabled). 

If you have the capacity, I would be glad to review PRs on this topic.

**Comment by lukasgr90** [comment]
I have extended the tests to cover my additions to the cloud config and thus I am now waiting on feedback.
