### ISSUE TITLE
Add repo/CI access for codeowners from STACKIT

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener-extension-os-coreos#97]
**How to categorize this issue?**

/area os open-source
/kind enhancement

**What would you like to be added**:

As part of https://github.com/gardener/gardener-extension-os-coreos/pull/96, @dergeberl and @timebertt are added as codeowners of this repository.

To the Gardener CI/CD team:
Can you ensure to grant us the following permissions, please?

- `maintain` permissions in this repository
- permission to trigger release pipelines for this repository

**Why is this needed**:

This will allow us to merge PRs, add other maintainers, and solve problems like [this](https://github.com/gardener/gardener-extension-os-coreos/pull/93#issuecomment-2020378263) and [this](https://github.com/gardener/gardener-extension-os-coreos/pull/96#issuecomment-2023850560).

**Comment by oliver-goetz** [comment]
@NiclasMoldenhauer please check Tim's request.
STACKIT is the main user of coreos extension, so it would make perfect sense, if they are able to maintain it too.

**Comment by NiclasMoldenhauer** [comment]
Approved from management side 👍

**Comment by zkdev** [comment]
@timebertt @dergeberl 

> permission to trigger release pipelines for this repository

You should have received an invitation for a GitHub Team in the meantime.
Once accepted, you should be able to trigger Concourse pipelines (you will have to re-auth in Concourse UI if you are logged-in already).
Could you please confirm that pipeline access is working as expected, e.g. by triggering an [head-update job](https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/gardener-extension-os-coreos-master/jobs/master-head-update-job/builds/1)?

---

> maintain permissions in this repository

Repository local `Write` role was assigned to you.
Administrative access to repositories is currently not available for external contributors.

---

> add other maintainers

Please request access for new maintainers via repository local GitHub issue (as with this issue).

**Comment by timebertt** [comment]
Thanks a lot, sounds good to me!

> Could you please confirm that pipeline access is working as expected, e.g. by triggering an [head-update job](https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/gardener-extension-os-coreos-master/jobs/master-head-update-job/builds/1)?

Works!

**Comment by dergeberl** [comment]
Thanks, 

> Could you please confirm that pipeline access is working as expected, e.g. by triggering an head-update job?

Works also for me :tada:

**Comment by zkdev** [comment]
@timebertt can we close this? :-)

**Comment by timebertt** [comment]
Yes, thanks!
/close
